update

diff --git a/sync_dotfiles b/sync_dotfiles
--- a/sync_dotfiles
+++ b/sync_dotfiles
@@ -3,42 +3,34 @@
 DOTFILES_DIR=$HOME/dotfiles
 GITHUB_REPO="git@github.com:LiuTaowen-Tony/dotfiles.git"
 
-# Check if the dotfiles directory exists
-if [ ! -d "$DOTFILES_DIR" ]; then
-    echo "Directory ~/dotfiles does not exist. Cloning from GitHub..."
-    # Clone the GitHub repository
-    git clone $GITHUB_REPO $DOTFILES_DIR
+if [ $# -ne 1 ]; then 
+  echo "please specify direction, u for upload, d for download"
+  exit 2
 fi
 
 FILES=( .tmux.conf .gitconfig )
-
 if [ -d "$HOME/.SpaceVim" ] ; then 
   FILES+=(".SpaceVim.d")
 else
   FILES+=(".vimrc")
 fi
 
-if [ $# -ne 1 ]; then 
-  echo "please specify direction, u for upload, d for download"
-  exit 2
-fi
 
 cd ${DOTFILES_DIR}
 
-if ! git pull; then 
-  echo "pull failed, please resolve manually"
+if ! git pull > /dev/null; then 
+  echo "sync_dotfiles : cannot pull from remote"
   exit 1
 fi
-echo "pulled from remote"
 
 if [ $1 == "u" ]; then
   for file in "${FILES[@]}"; do
     cp -r "$HOME/$file" $DOTFILES_DIR
   done
-  git add .
-  git commit -m "update"
+  git add . 
+  git commit -m "update" 
   if ! git push; then 
-    echo "push failed, please resolve manually"
+    echo "sync_dotfiles : push failed, please resolve manually"
     exit 1
   fi
 elif [ $1 == "d" ]; then
@@ -46,6 +38,7 @@ elif [ $1 == "d" ]; then
     cp -r "$DOTFILES_DIR/$file" $HOME
   done
 else 
-  echo "please specify direction, u for upload, d for download"
+  echo "sync_dotfiles : please specify direction, u for upload, d for download"
+  exit 1
 fi
 
